### ISSUE TITLE
Wiki request - rewrite and simplify explanation of HTML Entities

### ISSUE THREAD

**Issue by bugron** [FreeCodeCamp/wiki#354]
Original issue: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3412

http://dev.w3.org/html5/html-author/charref

**Comment by anuragaryan** [comment]
I'm not sure what do you want with these wiki requests, you want the solution of HTML Entities rewritten and explained or the questions?

**Comment by raisedadead** [comment]
@anuragaryan The links mentioned in the issue description are common resources for topics such as using HTML char codes in this case. We want explanatory articles on using them so that campers and anyone in general can find and use these easily.

If you need any assistance in writing or understanding please ping us in the [WikiChat room](https://gitter.im/FreeCodeCamp/Wiki), thanks.

**Comment by awesomeaniruddh** [comment]
I can work on this.
