### ISSUE TITLE
Article: Text Editors

### ISSUE THREAD

**Issue by theflametrooper** [FreeCodeCamp/wiki#653]
An article similar to #651. Will include content about the most popular free and paid text editors. Should also explain what a text editor is and the difference between a text editor and a full IDE.

**Comment by theflametrooper** [comment]
I'll work on this!

**Comment by alayek** [comment]
@Rafase282 I cannot assign @theflametrooper, because his name is not showing up in the list. Can we assign people who are not members?

**Comment by Rafase282** [comment]
@alayek I guess they need to be part of FCC github group.

**Comment by alayek** [comment]
@theflametrooper no worries. Work on your own pace, and submit a PR when you are ready. Just refer to this issue when  you are raising the PR.  Something like 
> Closes #653

**Comment by abhisekp** [comment]
I think this is a duplicate of https://github.com/FreeCodeCamp/wiki/issues/598

**Comment by raisedadead** [comment]
@theflametrooper Please do not include issue no.s in commits. :wink: 
On a side note can you confirm if this issue is not a duplicate than one that's pointed in the comment above. If yes would you mind closing this? Else you could ignore this request.

We are welcome to the PR though! Thanks a lot for contributing.

**Comment by theflametrooper** [comment]
This will be closed as duplication of #664
