### ISSUE TITLE
Github Flavored Markdown Doesn't Render Well on Main Site

### ISSUE THREAD

**Issue by zenware** [FreeCodeCamp/wiki#696]
https://www.dropbox.com/s/5b5tb5sppego2nr/Screenshot%202016-04-07%2019.31.51.png?dl=0

See https://www.freecodecamp.com/wiki/en/list-of-free-code-camp-city-based-campsites/

**Comment by abhisekp** [comment]
Looks like something is broken :broken_heart: 
cc: @awesomeaniruddh and @SaintPeter

**Comment by awesomeaniruddh** [comment]
@abhisekp @zenware Is this GitHub flavoured MDown? I've never seen it before.

```
[[create a Campsite for your city|How-to-create-a-Campsite-for-your-city]]
```

I'm not sure how images work in the wiki, but the issue seems to be that the img URL is relative and because the image is hosted on GitHub and not FreeCodeCamp, it's returning a 404 when viewed from freecodecamp.com

I suggest replacing the relative link with: `https://raw.githubusercontent.com/FreeCodeCamp/wiki/master/google-campsites-map.png` which should fix it.


```
[![Google Map of Campsites](google-campsites-map.png)](https://www.google.com/maps/d/u/0/embed?mid=zH0hxoM17_fk.kDBMlxfk0BZ8)
```

**Comment by zenware** [comment]
I think so, it's coming straight from the content of the github wiki page, and it renders correctly on the page in this repository. I'll post another screenshot tomorrow morning unless someone bothers to do it firsrt.

**Comment by zenware** [comment]
Here is how it renders on the [github page:](https://github.com/FreeCodeCamp/wiki/blob/834c0c9781bc1c5dd980b25e3ec0be36369041fb/List-of-Free-Code-Camp-city-based-Campsites.md) https://www.dropbox.com/s/110hdjvc3yfnn7r/Screenshot%202016-04-08%2011.31.02.png?dl=0
