### ISSUE TITLE
Multiple Home Links on Main Wiki

### ISSUE THREAD

**Issue by alayek** [FreeCodeCamp/wiki#721]
There are multiple links to home present on the main wiki at the moment. Here's a screen-shot I have taken

![wiki](https://cloud.githubusercontent.com/assets/5607371/14460839/5a7937b6-00dd-11e6-9757-022e75a16380.png)

**Comment by abhisekp** [comment]
@QuincyLarson @BerkeleyTrue any idea why this occurs? I've seen such things in other OSS project wikis too. So i suppose it's a GH bug?

**Comment by BerkeleyTrue** [comment]
It might be, but I don't have enough experience with it to say otherwise.

**Comment by lilyheart** [comment]
The pages list also includes all the pages from the other languages.  There are three other "Home" pages in the various localization folders.  I believe this accounts for the extra home pages.  I could test it  by changing one of those home files to something like fr.home (language prefix) and see if that moves it but that change might be better made by someone with direct access so the change can be reverted immediately if needed.

Note: The wiki pages in give no indication in the URL that they are in subfolders which is why I think all four home pages link to the same page: 
[**Example**: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Challenge-Informer-avec-l-Element-de-Paragraphe](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Challenge-Informer-avec-l-Element-de-Paragraphe)

**Comment by Rafase282** [comment]
They all point to the same home. Is not like one is pointing to a different language.

**Comment by lilyheart** [comment]
There is nothing different about the URL path on the files in the subf-olders (see the link I added at the end of my previous comment).  That would mean that a file in the top folder and a file in a sub-folder with the same name would have the same URL.

**Comment by Rafase282** [comment]
Int hat case, perhaps it would be best to have the name of the page in the target language?

**Comment by lilyheart** [comment]
Maybe preface every page in each language with the same prefix so they are found easier and show under pages grouped together?  E.g. FR:Page-Name

**Comment by Rafase282** [comment]
@lilyheart you were right. I renamed one of them and they worked. I'll make a PR with renaming all of them and we will also need to add this bit to the guidelines.

**Comment by Rafase282** [comment]
I just made the PR with the needed changes to fix this issue.

**Comment by Rafase282** [comment]
The changes has been made.
