### ISSUE TITLE
max-width to .wiki-container

### ISSUE THREAD

**Issue by xRahul** [FreeCodeCamp/wiki#753]
`max-width` css to the class `.wiki-container` is set to `960px` which is making the UI too narrow.
Need to remove that.

Without `max-width: 960px;`

![screenshot from 2016-04-19 10 57 07](https://cloud.githubusercontent.com/assets/1639945/14629548/22c94eee-0625-11e6-8472-631d18a9fa34.png)

With `max-width: 960px;`

![screenshot from 2016-04-19 10 56 31](https://cloud.githubusercontent.com/assets/1639945/14629549/22c9bafa-0625-11e6-9b61-ad4c8820784f.png)

**Comment by alayek** [comment]
@xRahul if `max-width: 960px` is removed, are you able to properly navigate horizontally to view the full image?

Also, this issue should be filed on the main repo: https://github.com/FreeCodeCamp/FreeCodeCamp because it's a site level presentation issue, not an issue with the content.

**Comment by xRahul** [comment]
@alayek Can you give an example of which image you're talking about?
I just checked on the wiki, and we can still do the horizontal scrolling after removing the max-width.

And this is an issue with the gh-pages branch of the wiki, not the main repo.

**Comment by raisedadead** [comment]
@xRahul Please log this on the main repo.

**Comment by xRahul** [comment]
@raisedadead @alayek  this is an issue with the `gh-pages` branch of wiki repo itself. It doesn't have anything to do with the main repo.
file: https://github.com/FreeCodeCamp/wiki/blob/gh-pages/styles.css

**Comment by raisedadead** [comment]
@xRahul Thanks. 

Its not about the location of the code. @alayek, myself couldn't be more correct in saying where the issue needs to be logged, considering that's our primary responsibility.

FYI, I'll give you how I reached the conclusion of pointing you to the main repo. Check [these issues](https://github.com/FreeCodeCamp/FreeCodeCamp/labels/wiki).

The `gh-pages` is supposed to be deployed via scripts via [this generator](https://github.com/FreeCodeCamp/wiki-generator), which is later embedded in an iframe in at `/wiki` on the main website.

Berkeley did some quick routing and CSS fixes since gatsby that the wiki-generator depends upon is now under works. You are more than welcome to take a look at the generator and come up with fixes.

As sure we need all the help we can get, but its not cool to dandy in and just say:
> this is an issue with the gh-pages branch of wiki repo itself. It doesn't have anything to do with the main repo.

The issues are triage-ed for valid reasons.

P.S : My comments are are against your comments and not your work. I sincerely thank you for the PR and the issue.

**Comment by xRahul** [comment]
@raisedadead Thanks for explaining the process. I really wasn't clear on how the wiki is being maintained. 
I've just looked into the the issues & the generator being used for the wiki and finally get what you guys have been talking about.

I will check out the generator more in detail, though you guys will have to help me out here as I'm still not clear about a lot of things related to the project.

**Comment by raisedadead** [comment]
@xRahul Sure thing! 

Feel free to seek any assistance in the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).
Do leave messages there and someone will respond surely, helping you out in anyway they can. 

Thanks again for contributing!
