### ISSUE TITLE
Create Article: Simple Angular2 App

### ISSUE THREAD

**Issue by abhisekp** [FreeCodeCamp/wiki#765]
<h1 align="center">ng Simplified</h1>

Write an article to create a **Basic Angular2 app**. :v:
<br>
<br>

> ----
<p align="center">Read <a href="https://github.com/FreeCodeCamp/wiki/blob/master/.github/CONTRIBUTING.md"><b>CONTRIBUTING</b></a> Guidelines<br>Chat with us in <kbd><a href="https://gitter.im/FreeCodeCamp/Wiki"><img src="http://i.imgur.com/ThSWa6Y.png?2"> <b>FreeCodeCamp/Wiki</b></a></kbd></p>

> ----

**Comment by dlwebdev** [comment]
Can I create this Angular2 tutorial? How basic? A simple component that displays text or a basic CRUD app such as the superheroes example that https://angular.io/docs/ts/latest/tutorial/ uses?

**Comment by alayek** [comment]
Hi @dlwebdev, thanks for your interest. Yes, sure!

Please create an article. But we would prefer it _did_ something. Rather than display *some hello world text*.

CRUD seems like a good coverage. But we are also not looking for something as extensive as a To-Do App.

---

You can simply start small. Show how to set up an Angular 2 seed project with TypeScript and all. Create a plunkr. Then, try to display some text. Maybe after that, some dynamic stuff.

**Comment by dlwebdev** [comment]
Feel free to criticize this in any way you'd like! My feelings won't get hurt.

I'd like to create a bit more in depth article about Angular 2 as well as one demonstrating a CRUD application. I think this one is a great start though. It links to two different plunkers. The first is a basic app that just displays some text. The second build upon the first and adds a button that shows clicks. It simply increments the click and shows the new value.
