### ISSUE TITLE
Should the wiki's be organized in respective directories?

### ISSUE THREAD

**Issue by sarbbottam** [FreeCodeCamp/wiki#898]
Currently all the `wiki` are stored in the root folder, `namespaced` with `category`. Wondering if they should be organized in respective directories.

For example; instead of `Algorithm-Binary-Agents.md`, organize it as `Algorithm/Binary-Agents.md`?

**Comment by theflametrooper** [comment]
@sarbbottam This sounds like an awesome idea! Tagging @Rafase282

**Comment by abhisekp** [comment]
If we do this, @camperbot needs to be adjusted to support this.

**Comment by sarbbottam** [comment]
It has to be a well thought approach. Otherwise the system, depending on current structure of Wiki will break.

What benefit could it offer?
- better file organization
- easier search/selection for wiki
<img width="500" alt="screen shot 2016-05-11 at 12 38 41 am" src="https://cloud.githubusercontent.com/assets/949380/15173411/c2c4709e-1710-11e6-8f6c-5bf7c2d6edfc.png">
- may be this could result in  a multi-level `drop down` instead of one gigantic list.
  - may be a top level drop down for `categories` which would map to `directories`
  - a second drop down for `wikis`, which gets filtered, w.r.t. the category selected.

**Comment by Rafase282** [comment]
We are going to remove the drop down entirely https://github.com/FreeCodeCamp/wiki-generator/issues/13.

With that in mind, there is no real benefit for this change. We already have subdirectories for different languages, which should hold the entire wiki all over for that particular language.

Also, while I have been working hard to categorize articles via their filenames, not all of them have it yet. Currently working on it https://github.com/FreeCodeCamp/wiki/issues/889 and not only camperbot would need to be update, but also the [wiki generator](https://github.com/FreeCodeCamp/wiki-generator).

Overall it is not a bad idea but currently alphabetical order and curated filenames will do. We have been renaming and changing the wiki internally and this will keep happening but we can't be changing our system every time which is the current debate with relative links and hard links, it was suggested, implemented, then it needed to be implemented on camperbot and the generator and while it was implemented in the generator (needs fixing now) it was never implemented on the bot, and some files require hardlinks which is something that will need to be addressed soon.

_Please note that I do not have anything against you or your ideas, they are welcome all the time. I only mention this because it seems to be the second time in a row that I say "no" to you and I don't want you to take it personal._

**Comment by sarbbottam** [comment]
> _Please note that I do not have anything against you or your ideas, they are welcome all the time. I only mention this because it seems to be the second time in a row that I say "no" to you and I don't want you to take it personal._

Not at all, you know the current system much better than I do and you are doing a great job!

But closing an issue pointing to a `contributing.md` which contradicts the current state of the file, is of no help but more confusion for the contributor 😄 I hope you could be more precise.

>>Basically we don't want more than 3 solutions and for new solutions we need the new template implemented.

>Gotcha!! BTW, [**this wiki page already have more than three solutions**](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Missing-letters.md)!

I understand, addressing so many concerns, gets hectic,  but it might acts as a barrier for any new contributor. May be you could distribute the load among other members / collaborators.

---

>We are going to remove the drop down entirely FreeCodeCamp/wiki-generator#13.

>With that in mind, there is no real benefit for this change.

I am afraid, there is. The number of files is not going to decrease but increase over the time, it will be unmaintainable soon. 

Currently `apples`, `oranges`, `bananas`, `pears` all are in same bucket and `color` (`filename prefix`) is being used to identify them. If they were in distinct bucket, it would have been easier. 

At the bare minimum the `wiki` should be categorized as per https://www.freecodecamp.com/map.

>not only `camperbot` would need to be update, but also the `wiki generator`.

Yep, which could be a big change. Thats the reason I stated.

>>It has to be a well thought approach. Otherwise the systems, depending on current structure of Wiki will break.

**Having said so, the suggested change might not be feasible, when the sub systems (`wiki`, `camperbot`, `wiki generator`) are tightly coupled.**

This might be the good time to start thinking about decoupling the system, before it's too late.

**Comment by Rafase282** [comment]
> This might be the good time to start thinking about decoupling the system, before it's too late.

I agree.

> I am afraid, there is. The number of files is not going to decrease but increase over the time, it will be unmaintainable soon.

You are right.

> But closing an issue pointing to a contributing.md which contradicts the current state of the file, is of no help but more confusion for the contributor :smile: I hope you could be more precise.

This is not quite clear to me. Was it the links not working or something else? The homepage for the wiki already explains about the algorithm challenges, precisely because many people were trying to add their solutions and it was getting tedious to keep repeating why we didn't accept the PR, the reasoning and what we want instead so I put it at the very front of the wiki.

**Comment by sarbbottam** [comment]
>This is not quite clear to me. Was it the links not working or something else? The homepage for the wiki already explains about the algorithm challenges, precisely because many people were trying to add their solutions and it was getting tedious to keep repeating why we didn't accept the PR, the reasoning and what we want instead so I put it at the very front of the wiki.

The `current state of the file` and the `three solution rule` are contradictory. That confused me. To be honest, I did not comprehend, till you explicitly stated the `3 solutions rule`.

**Comment by Rafase282** [comment]
So, now I'm back to this topic. I'm in favor of the proposal of using directories for categories. Open for opinions and suggestions.

**Comment by abhisekp** [comment]
@camperbot must be made compatible with this change first.

**Comment by Rafase282** [comment]
Moving this here :point_right: : [May 15, 2016 2:58 AM](https://gitter.im/FreeCodeCamp/CoreTeam?at=57381e0364dbdadc7dec2d8c)

> @Rafase282 +1 for the directory structure. The issue creator is right. if we are planning to hit the milestone of over 1000+ articles, the sectioned categorization makes sense. Yup I agree that this has an over head of auditing the challenges and making changes to links, etc. But that is a good change in terms of paying our technical debt with the wiki being tightly coupled to the bot and the main website.

> @BerkeleyTrue @Rafase282 @QuincyLarson About the language specific file names, we do need to consider on thing, on our challenge seed we have a unique identifier for the seeds. This makes the challenge identifiable, but having challenge specific file names will break this flow, so can we add a hidden attribute to the wiki content that can identify it `<div class="display:none" id="unique identifier key">` 

>--- By @raisedadead

**Comment by Rafase282** [comment]
@abhisekp after the 16, can you work on camperbot? making sure it works with the current names and style and that it will support this?

I'll have to work on the wiki generator to make sure it supports this change after we take care of the actual wiki and camperbot.

**Comment by Rafase282** [comment]
I tried it on my own wiki and I like it.

![My Wiki](http://i.imgur.com/mOayrdk.png)

Looks organized, things are easier to find and so on. The regular wiki works regardless. I will have to check how it would affect the generator.

**Comment by raisedadead** [comment]
@Rafase282 :shipit:

**Comment by abhisekp** [comment]
@Rafase282 looks awesome and perfect and organized and great. :sparkles: 
I will see how to make the camperbot work with it. :+1: 

Can you please push it on a branch in the main wiki or maybe in your fork?

**Comment by Rafase282** [comment]
@abhisekp it is on [this](https://github.com/Rafase282/MyFCCWiki) repo. Not for FCC. I haven't done it on it. Just wanted to try it on my end and see if I liked it and how links would change but links didnt change on the wiki.

**Comment by Rafase282** [comment]
This was a good idea and next on the list but we have migrated the wiki to the forum now. Thank you for your suggestion.
